README.md

add some additional documentation for sha256 github releases

---

extensions.json

add smtp extension

---

extensions.json

add discordbot

---

.github/workflows/validate.yml

add workflow for json validation

JSON validation, github workflow

---

extensions.json

https://github.com/lnbits/subdomains

add subdomains

---

extensions.json

https://github.com/lnbits/livestream

add livestream

---

extensions.json

fix boltz sha hash

---

extensions.json

https://github.com/lnbits/market
Webshop/market on LNbits

add market

---

extensions.json

release bugfix version for market

---

extensions.json

add paywall

---

extensions.json

https://github.com/lnbits/withdraw

add withdraw

---

.github/workflows/check.yml
check.py

simple sanity check for extensions.json
- checks whether provided archive files exists and whether the hashes match
- checks whether icon is a valid image file (via PIL)

add a simple check for checking extensions.json

---

extensions.json

https://github.com/lnbits/lndhub

add lndhub

---

extensions.json

https://github.com/lnbits/lnaddress

add lnaddress

---

extensions.json

bump satspay to 0.2

---

extensions.json

bump tipjar to 0.2

---

extensions.json

add feature, update existing lnurldevice via the UI

bump lnurldevice

---

extensions.json

For Americans to push payments to their Strike accounts.

Added strike

---

extensions.json

Update Gerty extension to 0.1.3

---

README.md

Fix typo in filename for extensions.json in README

Fix typo in filename of extensions.json in README

---

extensions.json

update lnurldevice to 0.4

---

extensions.json

update boltz to 0.2.2

---

extensions.json

https://github.com/lnbits/watchonly/releases/tag/v0.2.1

chore: bump watchonly to v0.2

---

README.md

update readme, wget instead of curl

---

extensions.json

update to copilot 0.4.1

---

extensions.json

update lnurlp to 0.3.1

---

extensions.json

update events to 0.1.2

---

extensions.json

Release Notes:
https://github.com/lnbits/satspay/releases/tag/0.2.3

chore: bump SatsPay to 0.2.3

---

extensions.json

release notes: https://github.com/lnbits/boltcards/releases/tag/0.0.2

[CHORE] update boltcards to 0.0.2

---

README.md
package.json
util.sh

usage: `sh util.sh update_extension example v0.4.2`

[FEAT] util.sh update extensions.json with jq

---

util.sh

[BUGFIX] remove v from version string

---

extensions.json

https://github.com/lnbits/example/releases/v0.3.0

[UPDATE] example to v0.3.0

---

util.sh

closes https://github.com/lnbits/lnbits-extensions/issues/150

[FEAT] fail updatRE_extension script when release does not exist

---

src/index.jsx
src/index.scss

[BUG] fixup website, broken download link, and buttons

---

extensions.json

https://github.com/lnbits/example/releases/v0.3.1

[UPDATE] example to v0.3.1

---

extensions.json

https://github.com/lnbits/copilot/releases/v0.4.4

[UPDATE] copilot to v0.4.4

---

extensions.json

https://github.com/lnbits/nostrnip5/releases/v0.0.3

[UPDATE] nostrnip5 to v0.0.3

---

extensions.json

https://github.com/lnbits/bleskomat/releases/v0.1.1

[UPDATE] bleskomat to v0.1.1

---

extensions.json

https://github.com/lnbits/bleskomat/releases/v0.1.2

[UPDATE] bleskomat to v0.1.2

---

extensions.json

https://github.com/lnbits/boltcards/releases/v0.0.4

[UPDATE] boltcards to v0.0.4

---

extensions.json

https://github.com/lnbits/events/releases/v0.1.3

[UPDATE] events to v0.1.3

---

extensions.json

https://github.com/lnbits/example/releases/v0.3.2

[UPDATE] example to v0.3.2

---

extensions.json

https://github.com/lnbits/gerty/releases/v0.1.5

[UPDATE] gerty to v0.1.5

---

extensions.json

https://github.com/lnbits/invoices/releases/v0.2.1

[UPDATE] invoices to v0.2.1

---

extensions.json

https://github.com/lnbits/jukebox/releases/v0.2.5

[UPDATE] jukebox to v0.2.5

---

extensions.json

https://github.com/lnbits/livestream/releases/v0.1.1

[UPDATE] livestream to v0.1.1

---

extensions.json

https://github.com/lnbits/lnaddress/releases/v0.2.1

[UPDATE] lnaddress to v0.2.1

---

extensions.json

https://github.com/lnbits/lndhub/releases/v0.3.1

[UPDATE] lndhub to v0.3.1

---

extensions.json

https://github.com/lnbits/lnticket/releases/v0.4.1

[UPDATE] lnticket to v0.4.1

---

extensions.json

https://github.com/lnbits/lnurldevice/releases/v0.5.6

[UPDATE] lnurldevice to v0.5.6

---

extensions.json

https://github.com/lnbits/lnurlp/releases/v0.3.2

[UPDATE] lnurlp to v0.3.2

---

extensions.json

https://github.com/lnbits/nostrnip5/releases/v0.0.4

[UPDATE] nostrnip5 to v0.0.4

---

extensions.json

https://github.com/lnbits/offlineshop/releases/v0.1.2

[UPDATE] offlineshop to v0.1.2

---

extensions.json

https://github.com/lnbits/paywall/releases/v0.2.1

[UPDATE] paywall to v0.2.1

---

extensions.json

https://github.com/lnbits/satsdice/releases/v0.1.1

[UPDATE] satsdice to v0.1.1

---

extensions.json

https://github.com/lnbits/scrub/releases/v0.3.1

[UPDATE] scrub to v0.3.1

---

extensions.json

https://github.com/lnbits/splitpayments/releases/v0.1.1

[UPDATE] splitpayments to v0.1.1

---

extensions.json

https://github.com/lnbits/streamalerts/releases/v0.2.1

[UPDATE] streamalerts to v0.2.1

---

extensions.json

https://github.com/lnbits/subdomains/releases/v0.1.1

[UPDATE] subdomains to v0.1.1

---

extensions.json

https://github.com/lnbits/tipjar/releases/v0.2.3

[UPDATE] tipjar to v0.2.3

---

extensions.json

https://github.com/lnbits/tpos/releases/v0.4.2

[UPDATE] tpos to v0.4.2

---

extensions.json

https://github.com/lnbits/watchonly/releases/v0.2.2

[UPDATE] watchonly to v0.2.2

---

extensions.json

https://github.com/lnbits/usermanager/releases/v0.3.1

[UPDATE] usermanager to v0.3.1

---

extensions.json

https://github.com/lnbits/usermanager/releases/v0.3.2

[UPDATE] usermanager to v0.3.2

---

extensions.json

https://github.com/lnbits/satspay/releases/v0.2.4

[UPDATE] satspay to v0.2.4

---

extensions.json

https://github.com/lnbits/nostrclient/releases/v0.3.2

[UPDATE] nostrclient to v0.3.2

---

extensions.json

https://github.com/lnbits/lnurldevice/releases/v0.5.7

[UPDATE] lnurldevice to v0.5.7

---

extensions.json

https://github.com/lnbits/usermanager/releases/v0.4.0

[UPDATE] usermanager to v0.4.0

---

extensions.json

https://github.com/lnbits/gerty/releases/v0.1.6

[UPDATE] gerty to v0.1.6

---

extensions.json

https://github.com/lnbits/lnurlp/releases/v0.3.3

[UPDATE] lnurlp to v0.3.3

---

extensions.json

https://github.com/lnbits/invoices/releases/v0.2.2

[UPDATE] invoices to v0.2.2

---

util.sh

fix: make utils.sh compatible with multiple releases

---

extensions.json

https://github.com/lnbits/withdraw/releases/v0.1.4

[UPDATE] withdraw to v0.1.4

---

extensions.json

https://github.com/lnbits/livestream/releases/v0.1.2

[UPDATE] livestream to v0.1.2

---

extensions.json

https://github.com/lnbits/copilot/releases/v0.4.6

[UPDATE] copilot to v0.4.6

---

extensions.json

https://github.com/lnbits/splitpayments/releases/v0.1.2

[UPDATE] splitpayments to v0.1.2

---

extensions.json

https://github.com/lnbits/offlineshop/releases/v0.1.3

[UPDATE] offlineshop to v0.1.3

---

extensions.json

[UPDATE] deezy to v0.2.0

---

extensions.json

https://github.com/lnbits/cashu/releases/tag/0.3.0

[UPDATE] update cashu to 0.3.0

---

extensions.json

https://github.com/lnbits/tpos/releases/v0.4.3

[UPDATE] tpos to v0.4.3

---

extensions.json

https://github.com/lnbits/market/releases/v0.2.2

[UPDATE] market to v0.2.2

---

extensions.json

https://github.com/lnbits/lnurldevice/releases/v0.5.8

[UPDATE] lnurldevice to v0.5.8

---

extensions.json

https://github.com/lnbits/satspay/releases/v0.2.5

[UPDATE] satspay to v0.2.5

---

extensions.json

https://github.com/lnbits/lndhub/releases/v0.3.2

[UPDATE] lndhub to v0.3.2

---

extensions.json

https://github.com/lnbits/nostrclient/releases/v0.3.7

[UPDATE] nostrclient to v0.3.7

---

extensions.json

https://github.com/lnbits/nostrmarket/releases/v0.5.1

[UPDATE] nostrmarket to v0.5.1

---

extensions.json

https://github.com/lnbits/satspay/releases/v0.2.6

[UPDATE] satspay to v0.2.6

---

extensions.json

https://github.com/lnbits/lnurlp/releases/v0.4.0

[UPDATE] lnurlp to v0.4.0

---

extensions.json

https://github.com/lnbits/tpos/releases/v0.5.0

[UPDATE] tpos to v0.5.0

---

extensions.json

https://github.com/lnbits/lnurlp/releases/v0.4.1

[UPDATE] lnurlp to v0.4.1

---

extensions.json

https://github.com/lnbits/lnurlp/releases/v0.4.2

[UPDATE] lnurlp to v0.4.2

---

extensions.json

https://github.com/lnbits/lnurlp/releases/v0.4.3

[UPDATE] lnurlp to v0.4.3

---

extensions.json

https://github.com/lnbits/lnurlp/releases/v0.4.4

[UPDATE] lnurlp to v0.4.4

---

extensions.json

https://github.com/lnbits/boltz/releases/v0.3.1

[UPDATE] boltz to v0.3.1

---

extensions.json

https://github.com/lnbits/tipjar/releases/v0.2.4

[UPDATE] tipjar to v0.2.4

---

extensions.json

https://github.com/lnbits/tpos/releases/v0.5.2

[UPDATE] tpos to v0.5.2

---

extensions.json

https://github.com/lnbits/tpos/releases/v0.5.3

[UPDATE] tpos to v0.5.3

---

extensions.json

https://github.com/lnbits/boltcards/releases/v0.0.5

[UPDATE] boltcards to v0.0.5

---

extensions.json

https://github.com/lnbits/satsdice/releases/v0.1.3

[UPDATE] satsdice to v0.1.3

---

extensions.json

https://github.com/lnbits/events/releases/v0.1.4

[UPDATE] events to v0.1.4

---

extensions.json

https://github.com/lnbits/withdraw/releases/v0.1.5

[UPDATE] withdraw to v0.1.5

---

extensions.json

https://github.com/lnbits/paywall/releases/v0.3.0

[UPDATE] paywall to v0.3.0

---

extensions.json

https://github.com/lnbits/tpos/releases/v0.6.0

[UPDATE] tpos to v0.6.0

---

extensions.json

https://github.com/lnbits/satspay/releases/v0.2.7

[UPDATE] satspay to v0.2.7

---

extensions.json

https://github.com/lnbits/market/releases/v0.2.4

[UPDATE] market to v0.2.4

---

extensions.json

https://github.com/lnbits/tpos/releases/v0.6.3

[UPDATE] tpos to v0.6.3

---

extensions.json

https://github.com/lnbits/withdraw/releases/v0.1.6

[UPDATE] withdraw to v0.1.6

---

.github/workflows/jmeter.yml
.gitignore
Makefile
README.md
integration/extensions-enable-all.jmx
integration/fragments/init-account.jmx
integration/fragments/init-server.jmx
integration/lnurl.jmx
integration/tpos.jmx
integration/watchonly-satspay-tipjar.jmx
pyproject.toml
test.sh

this is the new home for integration tests for extension.
the main repo `lnbits/lnbits` will also use the main branch of the repo to run the same extension tests.

feat: add extension integration tests

---

.github/workflows/jmeter.yml

only run on PR now and use PR base.ref

fix: undefined pathname on PRs

---

integration/lnurlw-race.jmx

by vlad. https://github.com/lnbits/lnbits/pull/2332

test: add lnurlw race test

---

extensions.json

https://github.com/lnbits/nostrrelay/releases/v0.25.2

[UPDATE] nostrrelay to v0.25.2

---

extensions.json

chore: remove cashu

---

.gitignore

chore: ignore upgrades

---

extensions.json

this pr combines all the extension that are updated for `0.12.6` ruff n change.
https://github.com/lnbits/lnbits/pull/2377
closes #294 
closes #291 
closes #290 
closes #292 
closes #293 
closes #301

[UPDATE] extension for ruff n PR

---

integration/lnurl.jmx
integration/lnurlw-race.jmx

https://github.com/lnbits/withdraw/pull/30

test: fix race-lnurlw for latest withdraw

---

extensions.json

https://github.com/lnbits/withdraw/releases/v0.1.9

[UPDATE] withdraw to v0.1.9

---

extensions.json

https://github.com/lnbits/copilot/releases/v0.5.1

[UPDATE] copilot to v0.5.1

---

extensions.json

https://github.com/lnbits/subdomains/releases/v0.1.2

[UPDATE] subdomains to v0.1.2

---

extensions.json

https://github.com/lnbits/boltz/releases/v0.3.2

[UPDATE] boltz to v0.3.2

---

extensions.json

https://github.com/lnbits/scrub/releases/v0.3.2

[UPDATE] scrub to v0.3.2

---

extensions.json

https://github.com/lnbits/splitpayments/releases/v0.1.3

[UPDATE] splitpayments to v0.1.3

---

extensions.json

https://github.com/lnbits/paywall/releases/v0.3.1

[UPDATE] paywall to v0.3.1

---

extensions.json

https://github.com/lnbits/example/releases/v0.3.3

[UPDATE] example to v0.3.3

---

extensions.json

https://github.com/lnbits/events/releases/v0.1.7

[UPDATE] events to v0.1.7

---

extensions.json

https://github.com/lnbits/jukebox/releases/v0.2.7

[UPDATE] jukebox to v0.2.7

---

integration/fragments/init-server.jmx

Depends on: https://github.com/lnbits/lnbits/pull/2139

fix: endpoint changed with users UI

---

extensions.json

https://github.com/lnbits/lnurldevice/releases/v0.6.5
Changelog https://github.com/lnbits/lnurldevice/compare/v0.6.1...v0.6.5
* Adds comments to switches
* Adds extended description
* Some cleaning

[UPDATE] lnurldevice to v0.6.5

---

extensions.json

https://github.com/lnbits/smtp/releases/v0.2.1

[UPDATE] smtp to v0.2.1

---

extensions.json

https://github.com/lnbits/satspay/releases/v0.2.8

[UPDATE] satspay to v0.2.8

---

extensions.json

https://github.com/lnbits/market/releases/v0.2.5

[UPDATE] market to v0.2.5

---

extensions.json

https://github.com/lnbits/lnticket/releases/v0.4.2

[UPDATE] lnticket to v0.4.2

---

extensions.json

https://github.com/lnbits/lnaddress/releases/v0.2.2

[UPDATE] lnaddress to v0.2.2

---

extensions.json

https://github.com/lnbits/livestream/releases/v0.1.3

[UPDATE] livestream to v0.1.3

---

extensions.json

https://github.com/lnbits/jukebox/releases/v0.3.0

[UPDATE] jukebox to v0.3.0

---

extensions.json

https://github.com/lnbits/satspay/releases/v0.3.0

[UPDATE] satspay to v0.3.0

---

extensions.json

https://github.com/lnbits/nostrnip5/releases/v0.1.0

[UPDATE] nostrnip5 to v0.1.0

---

extensions.json

https://github.com/lnbits/usermanager/releases/v0.4.1

[UPDATE] usermanager to v0.4.1

---

extensions.json

https://github.com/lnbits/lndhub/releases/v0.4.1

[UPDATE] lndhub to v0.4.1

---

extensions.json

https://github.com/lnbits/streamalerts/releases/v0.3.0

[UPDATE] streamalerts to v0.3.0

---

extensions.json

https://github.com/lnbits/lndhub/releases/v0.4.2

[UPDATE] lndhub to v0.4.2

---

extensions.json

https://github.com/lnbits/boltz/releases/v0.5.0

[UPDATE] boltz to v0.5.0

---

toc.md

remove boilerplate  and add MIT

feat: update toc.md

---

extensions.json

https://github.com/lnbits/boltz/releases/v0.5.1

[UPDATE] boltz to v0.5.1

---

extensions.json

https://github.com/lnbits/boltz/releases/v0.5.2

[UPDATE] boltz to v0.5.2

---

extensions.json

https://github.com/lnbits/nostrnip5/releases/v0.1.1

[UPDATE] nostrnip5 to v0.1.1

---

extensions.json

Remove market, until someone has time to make a simple webshop with it.

Remove Market

---

.github/workflows/check.yml

fix: ci runs on main

---

extensions.json

https://github.com/lnbits/lncalendar/releases/v0.1.5

[UPDATE] lncalendar to v0.1.5

---

extensions.json

https://github.com/lnbits/withdraw/releases/v0.1.11

[UPDATE] withdraw to v0.1.11

---

extensions.json
integration/005_lnurlw-race.jmx
integration/scripts/lnurlw_check_executed_withdraws.js

Depends on: https://github.com/lnbits/lnbits/pull/2537
Expected to fail until the above PR is merged.

fix: check payment status field

---

extensions.json

https://github.com/lnbits/boltz/releases/v0.5.3

[UPDATE] boltz to v0.5.3

---

extensions.json

https://github.com/lnbits/discordbot/releases/v0.1.1

[UPDATE] discordbot to v0.1.1

---

extensions.json

https://github.com/lnbits/nostrnip5/releases/v0.2.6

[UPDATE] nostrnip5 to v0.2.6

---

extensions.json

https://github.com/lnbits/lnticket/releases/v0.5.1

[UPDATE] lnticket to v0.5.1

---

extensions.json
integration/006_watchonly-satspay-tipjar.jmx

https://github.com/lnbits/satspay/releases/v0.3.2

[UPDATE] satspay to v0.3.2

---

extensions.json

https://github.com/lnbits/withdraw/releases/v0.1.13

[UPDATE] withdraw to v0.1.13

---

extensions.json

https://github.com/lnbits/lnurlp/releases/v0.5.6

[UPDATE] lnurlp to v0.5.6

---

extensions.json

https://github.com/lnbits/nostrnip5/releases/v0.2.9

[UPDATE] nostrnip5 to v0.2.9

---

integration/001_extensions-enable-all.jmx
integration/004_tpos-pay-to-enable.jmx
integration/008_lnaddress-conflict.jmx
integration/009_example_upgrade.jmx
integration/010_nostrnip5.jmx
integration/fragments/init-server.jmx
integration/scripts/check_price_in_sats_vs_millisats.js
integration/scripts/nip5_check_referer_balance.js

Tests nostrnip5

---

extensions.json

https://github.com/lnbits/tpos/releases/v0.7.2

[UPDATE] tpos to v0.7.2

---

update_version.py
util.sh

backwards compatible change.
now it works when changing the `min_lnbits_version`

feat: use python script to update ext version

---

extensions.json

https://github.com/lnbits/tpos/releases/v1.0.0

[UPDATE] tpos to v1.0.0

---

extensions.json

https://github.com/lnbits/withdraw/releases/v1.0.0

[UPDATE] withdraw to v1.0.0

---

extensions.json

https://github.com/lnbits/watchonly/releases/v1.0.0

[UPDATE] watchonly to v1.0.0

---

extensions.json

https://github.com/lnbits/subdomains/releases/v1.0.0

[UPDATE] subdomains to v1.0.0

---

extensions.json

https://github.com/lnbits/streamalerts/releases/v1.0.0

[UPDATE] streamalerts to v1.0.0

---

extensions.json

https://github.com/lnbits/smtp/releases/v1.0.0

[UPDATE] smtp to v1.0.0

---

extensions.json

https://github.com/lnbits/scrub/releases/v1.0.0

[UPDATE] scrub to v1.0.0

---

extensions.json

https://github.com/lnbits/satspay/releases/v1.0.0

[UPDATE] satspay to v1.0.0

---

extensions.json

https://github.com/lnbits/satsdice/releases/v1.0.0

[UPDATE] satsdice to v1.0.0

---

extensions.json

https://github.com/lnbits/offlineshop/releases/v1.0.0

[UPDATE] offlineshop to v1.0.0

---

extensions.json

https://github.com/lnbits/nostrnip5/releases/v1.0.0

[UPDATE] nostrnip5 to v1.0.0

---

extensions.json

https://github.com/lnbits/paywall/releases/v1.0.0

[UPDATE] paywall to v1.0.0

---

extensions.json

https://github.com/lnbits/nostrrelay/releases/v1.0.0

[UPDATE] nostrrelay to v1.0.0

---

extensions.json

https://github.com/lnbits/lnurlp/releases/v1.0.0

[UPDATE] lnurlp to v1.0.0

---

extensions.json

https://github.com/lnbits/lnticket/releases/v1.0.0

[UPDATE] lnticket to v1.0.0

---

extensions.json

https://github.com/lnbits/lndhub/releases/v1.0.0

[UPDATE] lndhub to v1.0.0

---

extensions.json

https://github.com/lnbits/invoices/releases/v1.0.0

[UPDATE] invoices to v1.0.0

---

extensions.json

https://github.com/lnbits/livestream/releases/v1.0.0

[UPDATE] livestream to v1.0.0

---

extensions.json

https://github.com/lnbits/jukebox/releases/v1.0.0

[UPDATE] jukebox to v1.0.0

---

extensions.json

https://github.com/lnbits/gerty/releases/v1.0.0

[UPDATE] gerty to v1.0.0

---

extensions.json

https://github.com/lnbits/example/releases/v1.0.2

[UPDATE] example to v1.0.2

---

extensions.json

https://github.com/lnbits/events/releases/v1.0.0

[UPDATE] events to v1.0.0

---

extensions.json

https://github.com/lnbits/copilot/releases/v1.0.0

[UPDATE] copilot to v1.0.0

---

extensions.json

https://github.com/lnbits/boltz/releases/v1.0.0

[UPDATE] boltz to v1.0.0

---

extensions.json

https://github.com/lnbits/boltcards/releases/v1.0.0

[UPDATE] boltcards to v1.0.0

---

extensions.json

https://github.com/lnbits/bleskomat/releases/v1.0.0

[UPDATE] bleskomat to v1.0.0

---

extensions.json

https://github.com/lnbits/tipjar/releases/v1.0.1

[UPDATE] tipjar to v1.0.1

---

extensions.json

https://github.com/lnbits/tipjar/releases/v1.0.0

[UPDATE] tipjar to v1.0.0

---

extensions.json

https://github.com/lnbits/splitpayments/releases/v1.0.0

[UPDATE] splitpayments to v1.0.0

---

extensions.json

https://github.com/lnbits/nostrmarket/releases/v1.0.0

[UPDATE] nostrmarket to v1.0.0

---

extensions.json

https://github.com/lnbits/withdraw/releases/v1.0.1

[UPDATE] withdraw to v1.0.1

---

extensions.json

This allows for the `More` button to show for extensions.
Next step, add description and terms and conditions to extensions

chore: add missing details_link

---

extensions.json
integration/003_tpos.jmx

https://github.com/lnbits/tpos/releases/v1.0.1

[UPDATE] tpos to v1.0.1

---

extensions.json

https://github.com/lnbits/jukebox/releases/v1.0.1

[UPDATE] jukebox to v1.0.1

---

extensions.json

https://github.com/lnbits/copilot/releases/v1.0.1

[UPDATE] copilot to v1.0.1

---

extensions.json

https://github.com/lnbits/livestream/releases/v1.0.1

[UPDATE] livestream to v1.0.1

---

extensions.json

https://github.com/lnbits/lncalendar/releases/v1.0.2

[UPDATE] lncalendar to v1.0.2

---

extensions.json
integration/001_extensions-enable-all.jmx

https://github.com/lnbits/splitpayments/releases/v1.0.1

[UPDATE] splitpayments to v1.0.1

---

extensions.json

https://github.com/lnbits/offlineshop/releases/v1.0.1

[UPDATE] offlineshop to v1.0.1

---

extensions.json

https://github.com/lnbits/nostrnip5/releases/v1.0.1

[UPDATE] nostrnip5 to v1.0.1

---

extensions.json
integration/009_example_upgrade.jmx

https://github.com/lnbits/example/releases/v1.0.6

[UPDATE] example to v1.0.6

---

extensions.json

https://github.com/lnbits/jukebox/releases/v1.0.2

[UPDATE] jukebox to v1.0.2

---

extensions.json

https://github.com/lnbits/lnurlp/releases/v1.0.1

[UPDATE] lnurlp to v1.0.1

---

extensions.json

https://github.com/lnbits/coinflip/releases/v1.0.0

[UPDATE] coinflip to v1.0.0

---

extensions.json

https://github.com/lnbits/tpos/releases/v1.0.3

[UPDATE] tpos to v1.0.3

---

extensions.json

https://github.com/lnbits/eightball/releases/v1.0.0

[UPDATE] eightball to v1.0.0

---

extensions.json

https://github.com/lnbits/satspot/releases/v1.0.0

[UPDATE] satspot to v1.0.0

---

extensions.json

https://github.com/lnbits/satspay/releases/v1.0.1

[UPDATE] satspay to v1.0.1

---

extensions.json

https://github.com/lnbits/lncalendar/releases/v1.0.3
Fix the API section

[UPDATE] lncalendar to v1.0.3

---

extensions.json

https://github.com/lnbits/lncalendar/releases/v1.0.4

[UPDATE] lncalendar to v1.0.4

---

extensions.json

https://github.com/lnbits/nostrnip5/releases/v1.0.2

[UPDATE] nostrnip5 to v1.0.2

---

extensions.json

https://github.com/lnbits/tpos/releases/v1.0.4

[UPDATE] tpos to v1.0.4

---

extensions.json

https://github.com/lnbits/boltcards/releases/v1.0.1

[UPDATE] boltcards to v1.0.1

---

extensions.json

https://github.com/lnbits/lndhub/releases/v1.0.1

[UPDATE] lndhub to v1.0.1

---

extensions.json

https://github.com/lnbits/bleskomat/releases/v1.0.1

[UPDATE] bleskomat to v1.0.1

---

extensions.json

https://github.com/lnbits/nostrnip5/releases/v1.0.3

[UPDATE] nostrnip5 to v1.0.3

---

extensions.json

https://github.com/lnbits/nostrnip5/releases/v1.0.4

[UPDATE] nostrnip5 to v1.0.4

---

extensions.json

https://github.com/lnbits/nwcprovider/releases/v1.0.0

[UPDATE] nwcprovider to v1.0.0

---

extensions.json

https://github.com/lnbits/bitcoinswitch_extension/releases/v1.0.1

[UPDATE] bitcoinswitch_extension to v1.0.1

---

extensions.json

https://github.com/lnbits/tpos/releases/v1.0.5

[UPDATE] tpos to v1.0.5

---

extensions.json

https://github.com/lnbits/nostrrelay/releases/v1.0.1

[UPDATE] nostrrelay to v1.0.1

---

extensions.json

https://github.com/lnbits/nwcprovider/releases/v1.0.1

[UPDATE] nwcprovider to v1.0.1

---

extensions.json

https://github.com/lnbits/invoices/releases/v1.1.0

[UPDATE] invoices to v1.1.0

---

extensions.json

https://github.com/lnbits/boltcards/releases/v1.0.3

[UPDATE] boltcards to v1.0.3

---

extensions.json

https://github.com/lnbits/lnurlp/releases/v1.1.0

[UPDATE] lnurlp to v1.1.0

---

extensions.json

https://github.com/lnbits/tpos/releases/v1.1.0

[UPDATE] tpos to v1.1.0

---

extensions.json

https://github.com/lnbits/satspot/releases/v1.2.0

[UPDATE] satspot to v1.2.0

---

extensions.json

https://github.com/lnbits/lnpos_extension/releases/v1.1.0

[UPDATE] lnpos_extension to v1.1.0

---

extensions.json

https://github.com/lnbits/coinflip/releases/v1.1.0

[UPDATE] coinflip to v1.1.0

---

extensions.json

https://github.com/lnbits/paywall/releases/v1.1.0

[UPDATE] paywall to v1.1.0

---

integration/002_lnurl.jmx

fix: jmeter test lnurlw decoder

---

extensions.json

https://github.com/lnbits/fossa_extension/releases/v1.2.0

[UPDATE] fossa_extension to v1.2.0

---

extensions.json

https://github.com/lnbits/splitpayments/releases/v1.1.0

[UPDATE] splitpayments to v1.1.0

---

.github/workflows/check.yml

remove pip cache. 
https://github.com/lnbits/lnbits-extensions/actions/runs/17427164916/job/49477005610

ci: fix jmeter fialing in cleanup tasks

---

extensions.json

https://github.com/lnbits/paidreviews/releases/v0.0.5

[UPDATE] paidreviews to v0.0.5

---

extensions.json

https://github.com/lnbits/numbers/releases/v1.0.3

[UPDATE] numbers to v1.0.3

---

extensions.json

https://github.com/lnbits/jukebox/releases/v1.0.4

[UPDATE] jukebox to v1.0.4
